### ISSUE TITLE
MusicXML output contains no 'system break' elements

### ISSUE THREAD

**Issue by Feles-Mala** [BreezeWhite/oemer#15]
**Describe the bug**

installed oemer today 1-10-22 using the quick start instructions on github page

sample scan taken on an iphone 13mini camera in good lighting and as orthogonal as possible; a simple grade 3 cello piece called barcarolle (attached jpeg). 

Apart from not getting the notes and rests quite the correct type, it has ignored the (seemingly identified, based on the preview image) system breaks, resulting in the staff being presented all on one long line. 

I can manually edit the xml to add:

<print new-system="yes">
        	<system-layout>
          		<system-margins>
            			<left-margin>0.00</left-margin>
            			<right-margin>879.94</right-margin>
            		</system-margins>
          		<system-distance>150.00</system-distance>
          	</system-layout>
	</print>

in the first measure of what should be a new line, and this presents as expected.

**Input Image**
Barcarolle.jpeg

**Full Traceback**
Not a code error, so no callstack

**Command You Execute**
oemer Barcarolle.jpeg

![2022-10-01 (2)](https://user-images.githubusercontent.com/110335095/193428468-90aba752-73d2-404a-bf59-9ed75a71f02c.png)

![Barcarolle jpeg_teaser](https://user-images.githubusercontent.com/110335095/193428366-c3772020-233f-45c4-855a-3d51d80e819c.png)

![Barcarolle](https://user-images.githubusercontent.com/110335095/193428350-a73abb5c-d453-4fa5-ab9b-75b9f690d171.jpeg)

**Comment by BreezeWhite** [comment]
Could you provide the original image (not the image name nor the image having bounding boxes)? Also the transcribed MusicXML file?

I assume the "system breaks" you mentioned means the stafflines don't properly switch to a newline, is that correct? What software are you using to view the output MusicXML file?

**Comment by Feles-Mala** [comment]
Hi @BreezeWhite 
The third image above is the input image I used; I scanned it rather than use a phone camera (for the second attempt).

images uploaded in initial report:
1- render using a c# control (the problem may lie here, but if i insert a break element it displays as expected)
2 - the tagged input image
3 - the raw scan I created.

I tried to upload the resultant musicxml file initially but the website balked. I have packaged two files into a zip as follows:
Barcarolle.musicxml - output file from oemer.
Barcarolle-test.musicxml - output file with manually added staff system break for new line

P.S. is there anything i can do about the incorrectly identified rest types? (Would you prefer I open different issues or are there things in the pipeline?)
[Barcarolle.zip](https://github.com/BreezeWhite/oemer/files/9713713/Barcarolle.zip)

**Comment by Feles-Mala** [comment]
Sorry, forgot to answer the rest of your questions. (perils of adhd)
yes, system breaks (as I understand it) are a newline element, though being fairly new to musicxml I'm not sure if they should be required or not.

I'm using a c# control from a suite called manufaktura, as I'm attempting to incorporate music score rendering in my own software. The library is a bit clunky (and I may switch if possible, if I can find a .net6 compatible one) but it has managed to render staff line breaks in downloaded musicxml files so far. Maybe there's a specification change?

It is possible the issue is not in oemer (which is brilliant by the way).

Happy to provide more files for comparison if required

**Comment by BreezeWhite** [comment]
I see. Since I usually use MuseScore to view the output MusicXML file, it handles the system breaks automatically and I did not implement to add such information in `oemer`. But this is achievable under current architecture of `oemer` to add system breaks. Maybe I could find some time to implement this.

Thanks for pointing out this ^^

**Comment by Feles-Mala** [comment]
re: rest type, that is intriguing, so it knows it's a rest but not which type? I could understand that between a semibreve and a minim rest, but this is where my image processing is very out of date so I won't embarass myself with a 'surely...' comment haha

thanks for the responses, I'll close this one and continue playing with scans.

Hope you don't mind if I post others though?

**Comment by Feles-Mala** [comment]
I tried MuseScore, and while it did show line breaks automatically it now hangs on startup continually, so I can't use it for verification anymore, dangit

**Comment by BreezeWhite** [comment]
> Unfortunately, the score renderer and musicxml loader doesn't allow clients much latitude in parsing control.

The output MusicXML file is just a text file, and thus you can open/edit it with any text editor. I'm not sure what do you mean about the clients doesn't allow parsing control?

> I'd be interested to know how musescore manages it automatically since some music syntax requires a fixed line break, so it can't just decide for itself can it?

I'm not familiar with this part neither... But I could guess that they handles the breaks by computing the noteheads sizes and spacing between them and setup some "good looking" rules to insert breaks properly. Something that is pretty similar to modern website will do like Responsive Web Design (RWD).

> re: rest type, that is intriguing, so it knows it's a rest but not which type?

Detailed algorithms can be found in README. In short, there are two steps for recognizing rest type. First is symbol type prediction by using deep learning models. The only thing it knows in this step is "the symbol is a rest, but I don't know whether is a eighth rest or quarter rest". The second step is to use another machine learning model called SVM, to identify the exact rest type, which bounds the accuracy rate due to its limitation. Lots of other handcrafted rules are also included during the recognition process.

> Hope you don't mind if I post others though?

Very welcome for any further suggestion or bug report~

> I'll close this one and continue playing with scans.

I think this is a good enhancement issue and I've already working on the system break issue. Therefore I'll reopen this issue and closing it again after the modification.

**Comment by BreezeWhite** [comment]
A new version has been released. Having fun~

**Comment by Feles-Mala** [comment]
Thanks so much @BreezeWhite I have been snowed under at work so not had a chance to give it a go, but I really appreciate the positive interaction :)
