### ISSUE TITLE
oemer can't read tab score

### ISSUE THREAD

**Issue by NeoMindStd** [BreezeWhite/oemer#21]
**Describe the bug**
oemer can't read tab score

**Input Image**
![treasure](https://user-images.githubusercontent.com/38518273/233660976-f619a09b-b6c1-42e3-ab3e-b7867a667304.jpg)

**Full Traceback**
[e oemer error 2023-04-21 231642 Ext.txt](https://github.com/BreezeWhite/oemer/files/11296587/e.oemer.error.2023-04-21.231642.Ext.txt)

**Command You Execute**
```python
        oemer_command = f'oemer -o "{output_file_name}" "{input_image_path}" '
        process = subprocess.Popen(oemer_command, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
```

**Comment by BreezeWhite** [comment]
Hi @NeoMindStd, thanks for the reporting. As the models and the whole system is designed to identify piano sheet, thus the result is expected: the system do not recognize tab score. There were also other people discussing to make system able to recognize other types of score. If you are interested in helping develop and improve the functionalities, you can go to the `Discussions` page.

Since the tab score scenario was not considered in `oemer`, this should not be a bug but improvement issue, thus closing this.

**Comment by NeoMindStd** [comment]
> > Hi @NeoMindStd, thanks for the reporting. As the models and the whole system is designed to identify piano sheet, thus the result is expected: the system do not recognize tab score. There were also other people discussing to make system able to recognize other types of score. If you are interested in helping develop and improve the functionalities, you can go to the `Discussions` page.
> > Since the tab score scenario was not considered in `oemer`, this should not be a bug but improvement issue, thus closing this.
> 
> Is there any tab recognition library you know of? I can't find it no matter how much I look for it 😢😢

Using [audiveris](https://github.com/Audiveris/audiveris), it is also possible to recognize tabs!
