### ISSUE TITLE
oemer[tf] fails to install

### ISSUE THREAD

**Issue by jdeluyck** [BreezeWhite/oemer#40]
**Describe the bug**
Oemer (tensorflow) requires tensorflow-gpu package, which has been retired:

```
     =========================================================
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      =========================================================
```

**Comment by EwingKang** [comment]
I tried installing tensorflow directly and calling oemer with `--use-tf` argument. It seems to work correctly with GPU and CUDA and CuDNN and all that. I'm unable to get the result due to my pitty 2GB VRAM MX150 laptop chip (got an OOM error), but I suspect it would work fine. The document requires modifications though.
p.s. I'm not installing this as a module using pip, but a standalone clone by itself.

**Comment by BreezeWhite** [comment]
I've updated the dependency and should fix the issue now.
